#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export DEBIAN_FRONTEND=noninteractive

# Install Ruby
sudo apt-get install -y ruby ruby-dev build-essential libpq-dev git
sudo sh -c 'echo "gem: --no-document" > /etc/gemrc'
sudo gem update --system
sudo gem install bundler

# Get the app's source code @master.
# You should actually checkout a specific branch or tag in order to get reproducibility.
git clone https://github.com/uhlig-it/journal.git
cd journal

# Install dependencies
bundle install --without development

# Migrate database to latest schema version
DB=$DB_URL rake db:migrate

# Register the app with systemd
sudo sh -c "DB=$DB_URL envsubst < /vagrant/etc/journal.service > /etc/systemd/system/journal.service"
sudo systemctl enable journal

# Start the app right away
sudo systemctl start journal
