#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

export DEBIAN_FRONTEND=noninteractive

apt-get --yes update
apt-get --yes install postgresql postgresql-client
su postgres -c "echo $DB_PASSWORD | createuser $DB_USER --password"
su postgres -c "createdb -O $DB_USER $DB_NAME"
echo "listen_addresses='*'" >> /etc/postgresql/*/main/postgresql.conf
echo "host all all $TRUSTED_NETWORK trust" >> /etc/postgresql/*/main/pg_hba.conf
service postgresql restart
